apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-volume
  labels:
    type: local
    app: nextcloud
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/nextcloud
