apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nextcloud
  name: nextcloud
spec:
  ports:
    - name: nextcloud
      port: 8081
      targetPort: 80
  selector:
    app: nextcloud
  type: LoadBalancer
  loadBalancerIP: 192.168.0.30
