apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      hostname: nextcloud-server
      containers:
        - image: nextcloud
          name: nextcloud
          env:
            - name: NEXTCLOUD_ADMIN_USER
              value: "napauleon2"
            - name: NEXTCLOUD_ADMIN_PASSWORD
              value: "#7!SgBPcNwvS27zpUrYzrp8$m"
            - name: NC_setup_create_db_user
              value: "false"
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud
      volumes:
        - name: nextcloud
          persistentVolumeClaim:
            claimName: nextcloud-volume-claim
