apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd-yaml
  name: httpd-yaml
spec:
  replicas: 10
  selector:
    matchLabels:
      app: httpd-yaml
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: httpd-yaml
    spec:
      containers:
        - image: httpd
          name: httpd
          #command: ["/bin/bash", "-c"]
          #args: ["sleep 5; exit 1"]
