apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: roon
  name: roon
spec:
  replicas: 10
  selector:
    matchLabels:
      app: roon
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: roon
    spec:
      containers:
        - image: steefdebruijn/docker-roonserver
          name: roon
          #command: ["/bin/bash", "-c"]
          #args: ["sleep 5; exit 1"]
