apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: roon
  name: roon
  annotations:
    external-dns.alpha.kubernetes.io/hostname: roon.home.io
    metallb.universe.tf/address-pool: default
spec:
  ports:
  - name: roon
    port: 9100
    targetPort: 9100
  selector:
    app: roon
  type: LoadBalancer
  loadBalancerIP: 192.168.0.30
